/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'zac.harvey' at '11/11/16 10:19 PM' with Gradle 2.14
 *
 * @author zac.harvey, @date 11/11/16 10:19 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
