/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'zac.harvey' at '11/11/16 10:19 PM' with Gradle 2.14
 *
 * @author zac.harvey, @date 11/11/16 10:19 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
